### ISSUE TITLE
First time scanning not detected

### ISSUE THREAD

**Issue by ijat** [reals79/wiegand-node#3]
Hi, i tried this library and it is great. Good job. Everything works but for the first time scanning my rfid tag, it does not detect. Then if i try second tag, it will be detected and working without any issue from now on. This only happen once each time the app started, so i have to scan one dummy tag to get it working.

I'm not familiar with weigand protocol and I think i missed something. Do you have any idea which part should i check? Thank you.

**Comment by Elompenta** [comment]
I can reproduce the same issue in my testsetup.
I have provided a pull request where you can start the wiegand module in a debug mode.
Can you provide the output ot them?

**Comment by ijat** [comment]
Sorry, I don't have the device anymore, so I can't provide the output. Btw, thanks for your effort.
